#!/bin/sh

if [ -n "$MYSQL_PASSWORD" ]; then
	echo "Dumping databases to: $RBU_CACHE/mysql.sql"
	mysqldump -u root -p${MYSQL_PASSWORD} --all-databases -r \
		$RBU_CACHE/mysql.sql
else
	echo "MySQL password not set, skipping mysqldump."
fi
