#!/bin/sh

if [ -n "$MYSQL_PASSWORD" ]; then
	echo "Dumping databases to: $BACKUP_CACHE/mysql.sql"
	[ -d "$CACHE_DIR" ] || mkdir -p "$BACKUP_CACHE"
	mysqldump -u root -p${MYSQL_PASSWORD} --all-databases -r \
		$BACKUP_CACHE/mysql.sql
else
	echo "MySQL password not set, skipping mysqldump."
fi
